# Final Minimal Version

Faces and incidents play a vital role in shaping our relations with other people, gradually detaching us from our usual instincts. With the ongoing pandemic, the use of video calling and social media platforms has grown significantly, and has leveraged our dependence of technology, completely ignoring the down-sides of this `audio-visual revolution`. All of this, increases the likelihood of transforming media into ones liking and thereby causing psychological manipulation of the society as a whole.

Since the very beginning of multimedia, people have always tried to fake genuine information for achieving deceptive motives. But deepfakes leverage powerful techniques from machine learning and artificial intelligence to manipulate or generate visual and audio content with a high potential to deceive general audience. The initial applications were intended to transform pipelines for filmmakers and 3D artists and effectively cut down on editing time.

The biggest dilemma that arises due to this is, “Can we ever trust the faces we see?”.  The post we see daily, the photographs, the video messages, the interviews, with faces of our know and trusted people, “is media even real?”. And speculations like these actually ignite minds to identify the fractures in this mechanism.

<img src="https://happymag.tv/wp-content/uploads/2021/06/tom-cruise-deepfake-technology-chris-ume-2021-e1624510366132.jpg" style="width: 100%; align: center;"/>

The current research on identifying a deepfake relies mainly on two approaches. The first one, that is extensively used by many leading Digital Forensic Experts, is by understanding the patterns of human body language, facial expressions, mouth movement and other Non-Verbal indication s, along with figuring out the weak spots that aren’t properly rendered like a generic video. This technique currently detects around 96% of the deepfakes successfully. But as the accuracy of ML is increasing, the surety of this technique’s predictions is quite uncertain.

On the other hand, researchers in big tech firms, like Google, Facebook and freelance enthusiast on platforms like Kaggle, Drivendata are working on their own machine learning perspectives to device a counteracting ML Model by reverse engineering the results from public datasets. As the research community looks to build upon these innovations, we should all think more broadly and consider solutions that go beyond analyzing images and video. Considering context, provenance, and other signals may be the way to improve deepfake detection models.

What we need to do is to trust the source of media generation, from where it is propagated and use common sense to understand that what you see is even plausible to you. One of the major cause of spread of misleading information, is the fact that they force us to think and react with almost no delay. We all need to take a second before finalizing our preconceptions and keep our eyes and ears open for anyone trying to invasively shape our believes.
